# MySQL connection settings.
spring.datasource.url=jdbc:mysql://localhost:3306/redbook?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=springstudent
spring.datasource.password=springstudent

# MySQL-specific Hibernate dialect.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
